import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import Nav from "@/components/nav";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { getProjects } from "@/lib/server";
import UserProvider from "@/components/user-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayou({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getKindeServerSession().getUser();
  const projects = user ? await getProjects(user.id) : null;

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="h-screen flex flex-col">
            <UserProvider user={user}>
              <Nav />
              {children}
            </UserProvider>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
